config/routes.rb
Rails.application.routes.draw do
  root "articles#index"

  resources :articles do
    resource :comments
  end

  resources :users

  get "/login", to: "users#login"
  get "/logout", to: "users#logout"

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  BANNED_KEYWORDS = %w[Harris Trump]
  TITLE_CONTAINS_BANNED_KEYWORDS_MESSAGE = "Post title contains a banned keyword"
  BODY_CONTAINS_BANNED_KEYWORDS_MESSAGE = "Post body contains a banned keyword"
  MINIMUM_BODY_LENGTH = 10
  include Visible
  has_many :comments
  belongs_to :user
  validates :title, presence: true
  validates :title, exclusion: { in: BANNED_KEYWORDS, message: TITLE_CONTAINS_BANNED_KEYWORDS_MESSAGE }
  validates :body, presence: true, length: { minimum: MINIMUM_BODY_LENGTH }
  validates :body, exclusion: { in: BANNED_KEYWORDS, message: BODY_CONTAINS_BANNED_KEYWORDS_MESSAGE }
  # validate :no_banned_keywords_in_title
  # private(
  #   def no_banned_keywords_in_title
  #     if title.present? && BANNED_KEYWORDS.any? { |word| title.downcase.include?(word) }
  #       errors.add(:title, "contains prohibited words")
  #     end
  #   end
  # )
end

app/models/comment.rb
class Comment < ApplicationRecord
  include Visible
  belongs_to :article
  belongs_to :user
end

app/models/concerns/visible.rb
module Visible
  extend ActiveSupport::Concern
  VALID_STATUSES = %w[public private archived]
  included do
    validates :status, inclusion: { in: VALID_STATUSES}
  end
  class_methods do
    def public_count
      where(status: "public").count
    end
  end
  def archived?
    status == "archived"
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_many :articles, dependent: :destroy
  has_many :comments, dependent: :destroy
  validates :username, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
  # before_action :require_login
  private
  def require_login
    unless session[:current_username]
      redirect_to login_path, alert: "Log in to access this page"
    end
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    # @articles = Article.all
    @articles = Article.order(created_at: :desc)
  end

  def show
    @article = Article.find(params[:id])
    @comment_count = @article.comments.count
  end

  def new
    @article = Article.new
  end

  def create
    @article = Article.new(article_params)
    puts "Current username", session[:current_username]
    @article.user = User.find_by(username: session[:current_username])
    if @article.user.nil?
      # TODO: Do something here.
      @article.user = User.create(username: session[:current_username])
    else
      @article.user.username = session[:current_username]
    end
    puts ""
    if @article.save
      redirect_to @article
    else
      puts @article.errors.full_messages
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @article = Article.find(params[:id])
  end

  def update
    @article = Article.find(params[:id])
    if @article.update(article_params)
      redirect_to @article
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    redirect_to root_path, status: :see_other
  end

  private
  def article_params
    params.require(:article).permit(:title, :body, :status)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @article = Article.find(params[:article_id])
    @comment = @article.comments.create(comment_params)
    redirect_to article_path(@article)
  end

  private
  def comment_params
    params.require(:comment).permit(:commenter, :body, :status)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  # skip_before_action :require_login, only: [:login]
  def login
    @user = User.new(user_params)
    if @user.save
      redirect_to @user
    else
      render :login, status: :unprocessable_entity
    end
  end
  def create
    # puts params[:user][:username]
    session[:current_username] = params[:user][:username]
    redirect_to root_path
  end
  def logout
    session[:current_username] = nil
  end
  private
  def user_params
    # params.require(:user).permit(:username)
    params.permit(:username)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_with model: article do |form| %>
  <div>
    <%= form.label :title %>
    <br>
    <%= form.text_field :title, class:"border-2 rounded-md my-2" %>
    <% article.errors.full_messages_for(:title).each do |message| %>
    <div>
      <%= message %>
    </div>
    <% end %>
  </div>

  <div>
    <%= form.label :body %>
    <br>
    <%= form.text_area :body, class:"border-2 rounded-md my-2" %>
    <br>
    <% article.errors.full_messages_for(:body).each do |message| %>
    <div class="border-2 rounded-md my-2 border-red-700 p-2">
      <%= message %>
    </div>
    <% end %>
  </div>

  <div>
    <%= form.label :status %>
    <br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: article.status || "public", class:"border-2 rounded-md my-2" %>
  </div>

  <div>
    <% if @article.errors.any? %>
    <span class="text-sm text-slate-400 font-bold">
      <%= pluralize(@article.errors.count, "error") %> prohibited this article from being saved:
    </span>
      <ul>
        <% @article.errors.full_messages.each do |message| %>
        <li class="px-4 py-2 border-2 rounded-md border-red-500">
          <%= message %>
        </li>
        <% end %>
      </ul>
    <% end %>
  </div>

  <div>
    <%= form.submit class:"inline-block bg-red-700 hover:bg-red-800 text-white rounded-md p-2 my-2" %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>
  Edit Article
</h1>

<%= render "form", article: @article %>

app/views/articles/index.html.erb
<h1 class="text-4xl mb-4 font-bold">
  Posts
</h1>
<div class="text-slate-400 text-sm">
  <% if !session[:current_username].nil? %>
    Currently logged in as
    <span class="font-bold hover:text-slate-500">
      <%= link_to session[:current_username], login_path %>
  </span>
    —
  <span class="hover:text-slate-500">
    <%= link_to "Log out", logout_path %>
  </span>
  <% else %>
    You are not currently logged in.
    <span class="font-bold hover:text-slate-600">
      <%= link_to "Log in", login_path %>
    </span>
  <% end %>
</div>
<ul>
  <% @articles.each do |article| %>
    <% unless article.archived? %>
      <li class="my-2 rounded-md border-2 py-2 px-4">
        <div class="text-2xl my-2 font-bold text-red-700 hover:text-red-800">
          <%= link_to article.title, article %>
        </div>
        <div class="text-slate-500 text-sm">
          Author:
          <% if !article.user.nil? && !article.user.username.nil? %>
            <%= article.user.username %>
          <% else %>
            Anonymous user
          <% end %>
        </div>
        <div class="p-2">
          <%= article.body %>
        </div>
        <div class="text-sm text-slate-400">
          Last updated:
          <%= article.updated_at %>
        </div>
        <div class="text-sm text-slate-400">
          <%= @comment_count %>
          comments
        </div>
      </li>
    <% end %>
  <% end %>
</ul>
<%= link_to "New Article", new_article_path, class: "inline-block bg-red-700 hover:bg-red-800 text-white rounded-md p-2 mt-4" %>

app/views/articles/new.html.erb
<h1 class="text-4xl mb-4 font-bold text-red-700">
  New Post
</h1>

<%= render "form", article: @article %>

app/views/articles/show.html.erb
<%= link_to "<- Back to all posts", articles_path, class: "text-slate-400 hover:text-slate-600" %>

<h1 class="text-4xl mb-4 text-red-700 font-bold my-2">
  <%= @article.title %>
</h1>

<p class="text-slate-400 text-sm">
  By
  <% if !@article.user.nil? %>
    <span class="font-bold">
      <%= @article.user.username %>
    </span>
  <% else %>
  <span class="font-bold">
    Anonymous author
  </span>
  <% end %>
</p>

<div class="px-4 py-2 rounded-md border-2 mt-2">
  <%= @article.body %>
</div>

<% if !@article.user.nil? && @article.user.username == session[:current_username] %>
  <ul>
    <li>
      <%= link_to "Edit", edit_article_path(@article), class: "inline-block bg-red-700 hover:bg-red-800 text-white rounded-md p-2 mt-2" %>
    </li>

    <li>
      <%= link_to "Destroy", article_path(@article), data: { turbo_method: :delete, turbo_confirm: "Are you sure?" }, class: "inline-block bg-red-700 hover:bg-red-800 text-white rounded-md p-2 mt-2" %>
    </li>
  </ul>
<% end %>

<h2>
  Comments
</h2>
<%= render @article.comments %>

<h2 class="text-2xl font-bold text-slate-600 my-2">
  Add a comment:
</h2>

<%= render "comments/form", article: @article %>

app/views/comments/_comment.html.erb
<% unless @article.archived? %>
  <p>
    <strong>
      Commenter:
    </strong>
    <%= comment.commenter %>
  </p>

  <p>
    <strong>
      Comment:
    </strong>
    <%= comment.body %>
  </p>
<% end %>

app/views/comments/_form.html.erb
<%= form_with model: [ article, article.comments.build ] do |form| %>
  <p>
    <%= form.label :commenter %>
    <br>
    <%= form.text_field :commenter %>
  </p>

  <p>
    <%= form.label :body %>
    <br>
    <%= form.text_area :body %>
  </p>

  <p>
    <%= form.label :status %>
    <br>
    <%= form.select :status, Visible::VALID_STATUSES, selected: "public" %>
  </p>

  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Blog" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- https://tailwindcss.com/docs/installation/play-cdn -->
    <script src="https://cdn.tailwindcss.com"></script>
  </head>

  <body class="px-12 py-12 md:px-60">
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with model: user do |form| %>
  <div>
    <%= form.label :username %>
    <%= form.text_field :username, class:"border-2 rounded-md my-2" %>
  </div>
  <div>
    <%= form.submit class:"inline-block bg-red-700 hover:bg-red-800 text-white rounded-md p-2 my-2" %>
  </div>
<% end %>

app/views/users/login.html.erb
<h1 class="text-4xl mb-4 font-bold text-red-700">
  Log In
</h1>

<%= render "form", user: @user %>

app/views/users/logout.html.erb
<div class="text-4xl text-red-700 font-bold">
  You have logged out
</div>

<div class="text-slate-400 hover:text-slate-600 mt-4">
  <%= link_to "Log in again", login_path %>
</div>